variables:
  # Cori queue submission options.
  SCHEDULER_PARAMETERS: "-C haswell -q debug -N1 -t 00:05:00"

# How is the workflow triggered?
workflow:
  rules:
    # Can only be initiated via a trigger token.
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always

# The CI job.
status-repo:

  # Running on Cori.
  tags: [cori]

  script:
    - python3 status-github.py

