variables:
  STATUS_SOURCE_REPO: https://software.nersc.gov/mcalpine/desc-continuous-integration.git
  STATUS_SOURCE_BRANCH: main
  STATUS_TARGET_REPO: https://github.com/stuartmcalpine/desc-continuous-integration.git
  STATUS_TARGET_CONTEXT: NERSC
  SCHEDULER_PARAMETERS: "-C haswell -q debug -N1 -t 00:05:00"

# Triggered from a trigger token (from MIRROR_SOURCE_REPO).
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always

status-repo:
  tags: [cori]
  script:
    - python3 status-github.py

