# Parameters of workflow.
variables:
  STATUS_SOURCE_REPO: https://software.nersc.gov/<namespace>/<source-repo-name>.git
  STATUS_SOURCE_BRANCH: main
  STATUS_TARGET_REPO: https://github.com/LSSTDESC/<target-repo-name>.git
  STATUS_TARGET_CONTEXT: NERSC
  SCHEDULER_PARAMETERS: "-C haswell -q debug -N1 -t 00:05:00"

# Can only be initiated via a trigger token.
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always

# The CI job.
status-repo:

  # Running on Cori.
  tags: [cori]

  script:
    - python3 status-github.py

