stages:
  - test


variables:
  SCHEDULER_PARAMETERS: "-C haswell -M escori -q xfer -N1 -t 01:00:00"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule"'
      when: always
  
      
example:
  stage: test
  tags: [cori]
  script: 
    - bash gitlab/example-test.bash 





