variables:
  SCHEDULER_PARAMETERS: "-C haswell -M escori -q xfer -N1 -t 01:00:00"
  GITLAB_PROJECT_NUMBER: 449

# Triggered from a trigger token (from MIRROR_SOURCE_REPO).
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always
  
      
example:
  tags: [cori]
  script: 
    - bash gitlab/example-test.bash 
    - curl -X POST --fail -F token=$STATUS_TRIGGER_TOKEN -F ref=main https://software.nersc.gov/api/v4/projects/$GITLAB_PROJECT_NUMBER/trigger/pipeline




