variables:
  # Cori queue submission options.
  SCHEDULER_PARAMETERS: "-C haswell -M escori -q xfer -N1 -t 01:00:00"

# How is this workflow triggered?
workflow:
  rules:
    # Can only be initiated via a trigger token.
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always

# The CI job.
example:

  # Running on Cori.
  tags: [cori]

  script:
    # Script loads desc-python Conda environment and runs tests.
    - bash examples/nersc_gitlab/example-test.bash 

    # Trigger the status repository CI workflow to report results.
    - >
      curl -X POST --fail
      --form "variables[GITLAB_STATUS_REPO]=$GITLAB_STATUS_REPO"
      --form "variables[GITLAB_TARGET_REPO]=$GITLAB_TARGET_REPO"
      --form "variables[GITLAB_MIRROR_REPO]=$GITLAB_MIRROR_REPO"
      --form "variables[GITHUB_SOURCE_REPO]=$GITHUB_SOURCE_REPO"
      --form "variables[GITHUB_SOURCE_BRANCH]=$GITHUB_SOURCE_BRANCH"
      --form "variables[GITLAB_TARGET_PROJECT_NUMBER]=$GITLAB_TARGET_PROJECT_NUMBER"
      --form "variables[GITLAB_MIRROR_PROJECT_NUMBER]=$GITLAB_MIRROR_PROJECT_NUMBER"
      --form "variables[GITLAB_STATUS_PROJECT_NUMBER]=$GITLAB_STATUS_PROJECT_NUMBER"
      --form "variables[GITLAB_STATUS_CONTEXT]=$GITLAB_STATUS_CONTEXT"
      --form "variables[GITHUB_SHA]=$GITHUB_SHA"
      --form token=$STATUS_TRIGGER_TOKEN
      --form ref=$GITHUB_SOURCE_REPO
      https://software.nersc.gov/api/v4/projects/$GITLAB_STATUS_PROJECT_NUMBER/trigger/pipeline
