variables:
  MIRROR_SOURCE_REPO: https://github.com/stuartmcalpine/desc-continuous-integration.git
  MIRROR_TARGET_REPO: https://software.nersc.gov/mcalpine/desc-continuous-integration.git
  SCHEDULER_PARAMETERS: "-C haswell -q debug -N1 -t 00:05:00"
  GITLAB_PROJECT_NUMBER: 445

# Triggered from a trigger token (from MIRROR_SOURCE_REPO).
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always

mirror-repo:
  tags: [cori]
  script:
    # 1) Script to mirror the GitHub repository.
    - bash mirror.bash
    # 2) Trigger the GitLab CI workflow in the target repository on GitLab.
    - curl -X POST --fail -F token=$TARGET_TRIGGER_TOKEN -F ref=main https://software.nersc.gov/api/v4/projects/$GITLAB_PROJECT_NUMBER/trigger/pipeline
