variables:
  # Cori queue submission options.
  SCHEDULER_PARAMETERS: "-C haswell -q debug -N1 -t 00:05:00"

# How is the workflow triggered?
workflow:
  rules:
    # Can only be initiated via a trigger token.
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always

# The CI Job.
mirror-repo:

  # Running on Cori.
  tags: [cori]

  script:
    # Script to mirror the GitHub repository.
    - bash mirror.bash

    # Trigger the GitLab CI workflow in the target repository on GitLab.
    - >
      curl -X POST --fail
      --form "variables[GITLAB_STATUS_REPO]=$GITLAB_STATUS_REPO"
      --form "variables[GITLAB_TARGET_REPO]=$GITLAB_TARGET_REPO"
      --form "variables[GITLAB_MIRROR_REPO]=$GITLAB_MIRROR_REPO"
      --form "variables[GITHUB_SOURCE_REPO]=$GITHUB_SOURCE_REPO"
      --form "variables[GITHUB_SOURCE_BRANCH]=$GITHUB_SOURCE_BRANCH"
      --form "variables[GITLAB_TARGET_PROJECT_NUMBER]=$GITLAB_TARGET_PROJECT_NUMBER"
      --form "variables[GITLAB_MIRROR_PROJECT_NUMBER]=$GITLAB_MIRROR_PROJECT_NUMBER"
      --form "variables[GITLAB_STATUS_PROJECT_NUMBER]=$GITLAB_STATUS_PROJECT_NUMBER"
      --form "variables[GITLAB_STATUS_CONTEXT]=$GITLAB_STATUS_CONTEXT"
      --form token=$TARGET_TRIGGER_TOKEN
      --form ref=main
      https://software.nersc.gov/api/v4/projects/$GITLAB_TARGET_PROJECT_NUMBER/trigger/pipeline
