# Parameters of workflow.
variables:
  MIRROR_SOURCE_REPO: https://github.com/LSSTDESC/<source-repo-name>.git
  MIRROR_TARGET_REPO: https://software.nersc.gov/<namespace>/<target-repo-name>.git
  SCHEDULER_PARAMETERS: "-C haswell -q debug -N1 -t 00:05:00"
  GITLAB_PROJECT_NUMBER: <target-repo-gitlab-project-number>

# Can only be initiated via a trigger token.
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always

# The CI Job.
mirror-repo:

  # Running on Cori.
  tags: [cori]

  script:
    # 1) Script to mirror the GitHub repository.
    - bash mirror.bash
    # 2) Trigger the GitLab CI workflow in the target repository on GitLab.
    - curl -X POST --fail -F token=$TARGET_TRIGGER_TOKEN -F ref=main https://software.nersc.gov/api/v4/projects/$GITLAB_PROJECT_NUMBER/trigger/pipeline
