# Define URLs for source and target repositories.
variables:
  MIRROR_SOURCE_REPO: https://github.com/LSSTDESC/desc-continuous-integration
  MIRROR_TARGET_REPO: https://software.nersc.gov/mcalpine/desc-continuous-integration
  SCHEDULER_PARAMETERS: "-C haswell -M escori -q xfer -N1 -t 01:00:00"

# How workflow is triggered.
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule"'
      when: always
  
# Run the mirror.bash script on Cori, which clones the GitHub repository.
example:
  tags: [cori]
  script:
    - bash mirror.bash
